name: "Docker Build Test Push"
description: "Build image, run tests and push to pkg.dev"

inputs:
  google_credentials:
    description: "Google credentials for registry"
    required: true
  registry:
    description: "Image registry to use"
    required: true
    default: "us-docker.pkg.dev"
  image:
    description: "Image name (without version tag)"
    required: true
  run_tests:
    description: "Run the tests job using docker-compose"
    required: true
    default: false
  additional_tag:
    description: "Additional tag to apply to the image"
    required: false
    default: ""

outputs:
  tags:
    description: "Image tags"
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: "Image labels"
    value: ${{ steps.meta.outputs.labels }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v0"
      with:
        credentials_json: "${{ inputs.google_credentials }}"
        token_format: "access_token"

    # Setup docker CLI
    - uses: "docker/login-action@v1"
      with:
        registry: "${{ inputs.registry }}"
        username: "oauth2accesstoken"
        password: "${{ steps.auth.outputs.access_token }}"

    # Setup buildx (used for registry-based cache)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Setup image metadata
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ inputs.registry }}/${{ inputs.image }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
          type=schedule,pattern={{date 'YYYYMMDD'}}
          type=raw,value=${{ inputs.additional_tag }},enable=${{ inputs.additional_tag != '' }}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build image locally for testing
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: ${{ inputs.registry }}/${{ inputs.image }}:test
        cache-from: type=registry,ref=${{ inputs.registry }}/${{ inputs.image }}:buildcache
        cache-to: type=registry,ref=${{ inputs.registry }}/${{ inputs.image }}:buildcache,mode=max

    - name: Test the image
      if: ${{ inputs.run_tests == 'true' }}
      run: |
        docker-compose -f docker-compose.test-image.yml up \
            --exit-code-from tests \
            --abort-on-container-exit \
            --force-recreate
      shell: bash

    - name: Build and push
      id: build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ inputs.registry }}/${{ inputs.image }}:buildcache
        cache-to: type=registry,ref=${{ inputs.registry }}/${{ inputs.image }}:buildcache,mode=max
