name: "Docker Build Test Push"
description: "Builds a docker image, runs tests if available, uploads to registry"

inputs:
  registry:
    description: "Image registry to use"
    required: true
    default: "us-docker.pkg.dev"
  image:
    description: "Image name (without version tag)"
  run_tests:
    description: "Run the tests job using docker-compose"
    required: true
    default: false

outputs:
  test:
    description: "Test output"
    value: ${{ steps.test.outputs.test }}

runs:
  using: "composite"
  steps:
    - id: test
      run: |
        echo "::set-output name=test::$(echo $RANDOM)"
        echo "${{ inputs.registry }}/${{ inputs.image }}"
      shell: bash

    - run: echo "Conditional step, should not run"
      if: inputs.run_tests
      shell: bash
