name: "Docker Build Test Push"
description: "Build image, run tests and push to pkg.dev"

inputs:
  google_credentials:
    description: "Google credentials for registry"
    required: true
  registry:
    description: "Image registry to use"
    required: true
    default: "us-docker.pkg.dev"
  image:
    description: "Image name (without version tag)"
  run_tests:
    description: "Run the tests job using docker-compose"
    required: true
    default: false

outputs:
  test:
    description: "Test output"
    value: ${{ steps.test.outputs.test }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v0"
      with:
        credentials_json: "${{ inputs.google_credentials }}"
        token_format: "access_token"

    # - id: test
    #   run: |
    #     echo "::set-output name=test::$(echo $RANDOM)"
    #     echo "${{ inputs.registry }}/${{ inputs.image }}"
    #   shell: bash

    # - run: echo "Conditional step, should not run"
    #   if: ${{ inputs.run_tests == 'true' }}
    #   shell: bash
