name: "Docker Build Test Push"
description: "Build image, run tests and push to pkg.dev"

inputs:
  google_credentials:
    description: "Google credentials for registry"
    required: true
  registry:
    description: "Image registry to use"
    required: true
    default: "us-docker.pkg.dev"
  image:
    description: "Image name (without version tag)"
    required: true
  build_args:
    description: "Build arguments to pass on to buildx"
    required: false
  run_tests:
    description: "Run the tests job using docker-compose"
    required: true
    default: "false"
  test_script:
    description: "Script to run for image testing"
    required: false
    default: |
      echo "ERROR: test_script not defined. Either define it or set run_tests to false" >&2
      exit 13
  test_build_args:
    description: "Build args for test build"
    required: false
  additional_tag:
    description: "Additional tag to apply to the image"
    required: false
    default: ""

outputs:
  tags:
    description: "Image tags"
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: "Image labels"
    value: ${{ steps.meta.outputs.labels }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Setup gcloud CLI
    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: "${{ inputs.google_credentials }}"
        token_format: "access_token"

    # Setup docker CLI
    - uses: "docker/login-action@v3"
      with:
        registry: "${{ inputs.registry }}"
        username: "oauth2accesstoken"
        password: "${{ steps.auth.outputs.access_token }}"

    # Setup buildx (used for registry-based cache)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Setup image metadata
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ inputs.registry }}/${{ inputs.image }}
        tags: |
          type=raw,value=${{ inputs.additional_tag }},enable=${{ inputs.additional_tag != '' }},priority=1500
          type=semver,pattern={{version}},priority=1300
          type=semver,pattern={{major}}.{{minor}}
          type=ref,event=branch
          type=ref,event=pr
          type=ref,event=tag
          type=sha
          type=raw,value={{date 'YYYYMMDD'}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build image locally for testing
      uses: docker/build-push-action@v6
      with:
        context: .
        load: true
        build-args: ${{ inputs.test_build_args }}
        tags: ${{ inputs.registry }}/${{ inputs.image }}:test
        cache-from: type=registry,ref=${{ inputs.registry }}/${{ inputs.image }}:buildcache
        cache-to: type=registry,ref=${{ inputs.registry }}/${{ inputs.image }}:buildcache,mode=max

    - name: Test the image
      if: ${{ inputs.run_tests == 'true' }}
      run: ${{ inputs.test_script }}
      shell: bash

    - name: Build and push
      id: build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ inputs.registry }}/${{ inputs.image }}:buildcache
        cache-to: type=registry,ref=${{ inputs.registry }}/${{ inputs.image }}:buildcache,mode=max
        build-args: |
          ${{ inputs.build_args }}
          DOCKER_METADATA_OUTPUT_VERSION
          DOCKER_METADATA_OUTPUT_TAGS
